### ISSUE TITLE
Todos don't show up and refreshing the view gives errors

### ISSUE THREAD

**Issue by CombustibleLemonade** [need12648430/godot-todo#2]
All shown by this image:
![image](https://cloud.githubusercontent.com/assets/3164190/23279122/5c6cad92-fa14-11e6-848d-aec7817f47b9.png)

**Comment by need12648430** [comment]
Should be fixed in 3b3a350. Let me know if you still have issues. You can just plop dock.gd over the old one to see.

**Comment by CombustibleLemonade** [comment]
The errors are now gone, but I still can't get any TODO's to show up. Is this how I'm supposed to write them?
`# FIXME: test `
`# TODO: test `

Furthermore, if I wait for a while, I get a new error when refreshing:
`
 res://addons/todo/dock.gd:38 - Invalid call. Nonexistent function 'get_node' in base 'Nil'.
`

**Comment by need12648430** [comment]
Are you modifying the dock.gd script at all? I've noticed it tends to break internally-stored references. If so, Godot needs to be restarted.

Is there any way you can send me a copy of the project in question? I'm not having any issues with TODOs showing up.

**Comment by CombustibleLemonade** [comment]
[Here's the repo I'm using it in](https://github.com/CombustibleLemonade/Vladimir)

**Comment by need12648430** [comment]
Just checked it out and opened it up in Godot. No issues. Shows TODOs, refreshes as expected, no errors.

I just pushed the update to the Asset Library last night, might be ready now. Try reinstalling godot-todo.

**Comment by CombustibleLemonade** [comment]
I just tried reinstalling godot-todo, and I tried running it on my laptop (which runs windows instead of linux), to no avail. Could you tell me what version of Godot you're using? I'm using the one from steam.

**Comment by need12648430** [comment]
Build of the latest commit on the 2.1 branch.
