### ISSUE TITLE
Don't know how to use this..

### ISSUE THREAD

**Issue by drarem** [need12648430/godot-todo#3]
Plugin installed and active. At top of a couple of .GD scripts, I have  /# had to put that to indicate i have a comment on the line, this html formatting is killing me. If I don't comment out the TODO: or the FIXME:  the script will error out.

/# TODO:  testing
and 
/# FIXME: this is a test

Nothing is showing in the tab, i rebooted godot (have latest stable 2..3, and 1.0.3 version of todo)

Thanks.

**Comment by drarem** [comment]
Here's script error:

SCRIPT ERROR: get_all_scripts: Attempt to call function 'get_script' in base 'null instance' on a null instance.
          At: res://addons/todo/dock.gd:127
SCRIPT ERROR: find_all_todos: Unable to iterate on object of type  Nil'.
          At: res://addons/todo/dock.gd:151
SCRIPT ERROR: populate_tree: Unable to iterate on object of type  Nil'.
          At: res://addons/todo/dock.gd:59

**Comment by ivanskodje** [comment]
Do you still have a problem?

**Comment by drarem** [comment]
Yes, put this in the main script gd file, and nothing shows up on TODO tab, even when i hit refresh.

#TODO this is a test

**Comment by ivanskodje** [comment]
You need to add a :

Try to format your comments like this:
`# TODO: This is a test`

**Comment by drarem** [comment]
ok thanks, now it's working. odd i couldn't get it right the first time.. will play further with it and see if i have other problems. It does show up twice in the TODO list but it's fine with me.

**Comment by ivanskodje** [comment]
I fixed the issue about showing up twice in the TODO list in a PR :)
https://github.com/need12648430/godot-todo/pull/4#issuecomment-307829495
