### ISSUE TITLE
Auto-Refresh causes the tree view to expand

### ISSUE THREAD

**Issue by ivanskodje** [need12648430/godot-todo#5]
May want to check that out

**Comment by need12648430** [comment]
Can't reproduce.

**Comment by ivanskodje** [comment]
- Create a bunch of TODO's in one GDScript.
- Close the tree for a script that contains TODO comments
- Refresh and watch the tree view expand again, even though you closed the tree

**Comment by need12648430** [comment]
Ah, okay. Will look into patching.

**Comment by Ranoller** [comment]
Edited:

Is posible to always start with the tree collapsed:
Add this line (with 3 Tabs) in dock.gd:

179:   file_node.set_collapsed(true)

To remember the collapsed/expanded state of any of the TreeItems the plugin must store that state in a dictonary with all files and make comprobation every "populate_tree" execution one by one(and store that on disk if you want remember that between godot editor executions), this is a bunch of lines of code and extra-functionality, not an issue. I think that contracted foders by default is ok.
