### ISSUE TITLE
Crash in proyects with error in any scene

### ISSUE THREAD

**Issue by Ranoller** [need12648430/godot-todo#7]
If install TODO plugin in a proyect that have any scene with errors (that impide instantiate), the plugin stop function (the problem is the code that  follows: "elif (file.extension().to_lower() in ["tscn", "xscn", "scn"]):" that try to instantiate files that can´t be instantiated. 

Other problem with that fragment of code: is extremely slow, in a"mid proyect", if I "comment" the "elif" part of the "find_all_todos" function to find TODOS only in gd files, the entire code of the plugin executes in 0 seconds, but if this code is executed and the plugin try to instantiate all TSCN and SCN files, the plugin delays several minutes in the execution (In proyect without scn files errors and medium size). I know that this is necesary to find text in embedded scripts but do the plugin x1000 times slower and unusable in mid-size proyects. My opinion is that this plugin don´t need to find text in embedded scripts or in scene files, and I think that nobody pack scripts.

Plugin without the scene instantiate part is very usefull, that should be integrated in Godot by default. I do a modification to dock scene and add a line-edit and a button to find any text, not only TODOS, and work very acurate, is like a "find in all archives" function from notepad++, I don´t know how git and github functions (this is my first message), but if somebody is interested in add the find text functionality of TODO and knows how to do that "commit" "pull" or whatever needs to be done i paste or send the code.

Sorry for the english...

**Comment by need12648430** [comment]
I will look into failing gracefully on corrupted scenes. Going by the ResourceLoader code, Godot returns a null Resource on failure - a case I neglected to handle. I'll patch it by tomorrow.

As for the slowing, a significant speed boost can be had with a proper cache system - only instantiating the scenes that have changed since the last check. There's no need to remove that feature, I just implemented it lazily. Feel free to comment out that block of code.

I wouldn't count on a cache being implemented for a little while though. I'll be rewriting this add-on for 3.0 anyway with stability and speed in mind, so any significant architectural overhauls here will largely go to waste. #5 will be closed then as well.

**Comment by Ranoller** [comment]
Good to know that the plugin have future for new versions :) :) :)

Aclaration to the failure in scenes:  My proyect had several scenes with broken links resources to files (textures...etc...) that I copied from other proyect. The proyect played correctly because this scenes weren´t in use. When i fixed that missings resources the plugin start to work.

I comment a usefull idea that i put in any plugin that scans for text in archives in proyect: a exclusion directory. I need that because I have an autoload that backups periodicaly my scripts in a numerated directories. And finding text returns duplicates, triplicates, etc... What i did is a var called IgnoreDir (var IgnoreDir = "res://AutoBackup") and put de code that is under the #MODIFICATION comment:

func find_files(directory, extensions, recur = false):
	# Create empty array that will store our results
	var results = []
	
	# Create directory variable
	var dir = Directory.new()
	
	# Attempt to open directory
	if(dir.open(directory) != OK):
		return results # Failed to open directory, return empty array
	
	#MODIFICATION:
	
	if directory == IgnoreDir: 
		return results

	# Initialise the stream used to list all files and directories
	dir.list_dir_begin()
	
	# Get our first file (which may also be a sub-directory)

This is usefull in your plugin and in "Proyect Analitics" (other very usefull plugin for godot).

The other functionality that i hack in your plugin (find text) is very usefull, but it need the scene attached with the modifications (new button and line-text) and not only the code to put here. I know that is very easy to do, and don´t know if you want to add this to your plugin, but if someday you want implement this and don´t want start from 0 (yes, is a 10 minutes of code but...) i send my plugin version. Thanks for your plugin!, script plugins for godot should follow this "utility" way.
